Update project dependencies and configuration files for .NET 9 compatibility

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -13,6 +13,9 @@ before_script:
   - 'echo "Hostname: $(hostname)"'
   - 'dotnet --info'
 
+variables:
+  GIT_CLONE_PATH: '$CI_BUILDS_DIR/$CI_PROJECT_NAME/$CI_PIPELINE_ID'
+
 restore:
   stage: build
   script:
@@ -30,11 +33,13 @@ lint:
   needs: 
     - build
   script:
-    - jb inspectcode ./*.sln --output=analyze_output.xml --build -f=xml
+    # 3 times retry because sometimes the first time will fail
+    - jb inspectcode ./*.sln --output=analyze_output.xml --build -f=xml || jb inspectcode ./*.sln --output=analyze_output.xml --build -f=xml || jb inspectcode ./*.sln --output=analyze_output.xml --build -f=xml
     # Remove the warning of UnusedAutoPropertyAccessor InconsistentNaming
     - sed -i '/InconsistentNaming/d' analyze_output.xml
     - sed -i '/AssignNullToNotNullAttribute/d' analyze_output.xml # This is because jetbrains is not smart enough to understand the nullability of C# 8.0
     - sed -i '/UnusedAutoPropertyAccessor/d' analyze_output.xml
+    - sed -i '/DuplicateResource/d' analyze_output.xml
     - grep 'WARNING' analyze_output.xml && cat analyze_output.xml && exit 1 || echo "No warning found"
   artifacts:
     when: always
@@ -79,22 +84,7 @@ pack:
     paths:
       - '**/*.nupkg'
 
-upload_to_nuget:
-  stage: deploy
-  environment: production
-  needs:
-    - pack
-  dependencies:
-    - pack
-  script:
-    - |
-      for file in $(find . -name "*.nupkg"); do
-        dotnet nuget push "$file" --api-key "$NUGET_API_KEY" --source "https://api.nuget.org/v3/index.json" --skip-duplicate || exit 1;
-      done
-  only:
-    - master
-
-upload_to_local_nuget:
+deploy_local_nuget:
   stage: deploy
   environment: production
   needs:
@@ -109,7 +99,23 @@ upload_to_local_nuget:
   only:
     - master
 
-deploy_docker:
+deploy_public_nuget:
+  stage: deploy
+  environment: production
+  needs:
+    - pack
+    - deploy_local_nuget
+  dependencies:
+    - pack
+  script:
+    - |
+      for file in $(find . -name "*.nupkg"); do
+        dotnet nuget push "$file" --api-key "$NUGET_API_KEY" --source "https://api.nuget.org/v3/index.json" --skip-duplicate || exit 1;
+      done
+  only:
+    - master
+
+deploy_docker_registry:
   stage: deploy
   environment: production
   needs: 
@@ -120,6 +126,24 @@ deploy_docker:
     - echo building image hub.aiursoft.cn/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$TAG
     - docker build . -t hub.aiursoft.cn/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
     - docker push hub.aiursoft.cn/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
+  rules:
+    - if: '$CI_COMMIT_BRANCH == "master"'
+      exists:
+      - Dockerfile
+
+deploy_docker_hub:
+  stage: deploy
+  environment: production
+  needs: 
+    - deploy_docker_registry
+  script:
+    - if [ "$CI_PROJECT_NAMESPACE" = "anduin" ]; then NAMESPACE="anduin2019"; else NAMESPACE="$CI_PROJECT_NAMESPACE"; fi
+    - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then TAG="latest"; else TAG="$CI_COMMIT_REF_NAME"; fi
+    - echo building image $NAMESPACE/$CI_PROJECT_NAME:$TAG
+    - docker build . -t $NAMESPACE/$CI_PROJECT_NAME:$TAG
+    - echo "Logging in to Docker Hub..."
+    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
+    - docker push $NAMESPACE/$CI_PROJECT_NAME:$TAG
   rules:
     - if: '$CI_COMMIT_BRANCH == "master"'
       exists:
